/**
 * 화장품 추천 DB 시드 데이터 — 카테고리별 50개, 총 250개
 * 출처: 올리브영 2025 어워즈, 화해 랭킹, 글로우픽 TOP20, 각종 뷰티 미디어
 * 바우만 타입 매핑: 주요 성분 + 제품 특성 기반 수동 매핑
 */

export interface ProductSeed {
  name: string;
  brand: string;
  category: "toner" | "serum" | "cream" | "sunscreen" | "cleanser";
  key_ingredients: string;    // JSON array
  best_baumann: string;       // JSON array
  avoid_baumann: string;      // JSON array
  target_concern: string;
  price: number;
}

export const PRODUCT_SEED: ProductSeed[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 토너 (50)
  // ═══════════════════════════════════════════════════════════════════════════
  { name: "1025 독도 토너", brand: "라운드랩", category: "toner", key_ingredients: '["해양심층수","히알루론산","판테놀"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 12000 },
  { name: "다이브인 저분자 히알루론산 토너", brand: "토리든", category: "toner", key_ingredients: '["히알루론산","판테놀","알란토인"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 18200 },
  { name: "어성초 77 수딩 토너", brand: "아누아", category: "toner", key_ingredients: '["어성초","판테놀","위치하젤"]', best_baumann: '["OSPT","OSPW","OSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 25000 },
  { name: "머금 에센스 토너", brand: "넘버즈인", category: "toner", key_ingredients: '["히알루론산","쌀추출물","나이아신아마이드"]', best_baumann: '["DSPT","DSPW","DRNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 18000 },
  { name: "원더 세라마이드 모찌 토너", brand: "토니모리", category: "toner", key_ingredients: '["세라마이드","히알루론산","판테놀"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 13600 },
  { name: "아쿠아 오아시스 토너", brand: "에스네이처", category: "toner", key_ingredients: '["스쿠알란","히알루론산","카밀레"]', best_baumann: '["DSPT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "hydration", price: 18000 },
  { name: "AHA BHA PHA 30 Days 미라클 토너", brand: "썸바이미", category: "toner", key_ingredients: '["AHA","BHA","PHA","나이아신아마이드"]', best_baumann: '["ORPT","ORPW","ORNT"]', avoid_baumann: '["DSPT","DSPW"]', target_concern: "pore", price: 12000 },
  { name: "시카페어 토너", brand: "닥터자르트", category: "toner", key_ingredients: '["센텔라","판테놀","마데카소사이드"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 23000 },
  { name: "그린티 히알루론산 토너", brand: "이니스프리", category: "toner", key_ingredients: '["녹차","히알루론산","스쿠알란"]', best_baumann: '["DRNT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 13500 },
  { name: "티트리 시카 수딩 토너", brand: "쏘내추럴", category: "toner", key_ingredients: '["티트리","시카","살리실산"]', best_baumann: '["OSPT","OSPW","ORPT"]', avoid_baumann: '["DSPT"]', target_concern: "acne", price: 12800 },
  { name: "마다가스카르 센텔라 토닝 토너", brand: "스킨1004", category: "toner", key_ingredients: '["센텔라","나이아신아마이드","히알루론산"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "soothing", price: 16000 },
  { name: "맑은 어성초 진정 토너", brand: "구달", category: "toner", key_ingredients: '["어성초","판테놀","알란토인"]', best_baumann: '["OSPT","OSNT","OSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 13500 },
  { name: "크림스킨 리파이너", brand: "라네즈", category: "toner", key_ingredients: '["세라마이드","펩타이드","아미노산"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 32000 },
  { name: "밀크 스킨 토너", brand: "틸틸", category: "toner", key_ingredients: '["폴리글루탐산","나이아신아마이드","히알루론산"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 28000 },
  { name: "자작나무 수분 토너", brand: "라운드랩", category: "toner", key_ingredients: '["자작나무수액","히알루론산","판테놀"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 15800 },
  { name: "PDRN 히알루론산 토너", brand: "아누아", category: "toner", key_ingredients: '["PDRN","히알루론산","나이아신아마이드"]', best_baumann: '["DSPW","DSPT","DRPW"]', avoid_baumann: '[]', target_concern: "repair", price: 23000 },
  { name: "레드 블레미쉬 클리어 수딩 토너", brand: "닥터지", category: "toner", key_ingredients: '["시카","센텔라","판테놀"]', best_baumann: '["OSPT","DSPT","OSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 18000 },
  { name: "갈락토미세스 퍼스트 에센스", brand: "마녀공장", category: "toner", key_ingredients: '["갈락토미세스","나이아신아마이드","히알루론산"]', best_baumann: '["DRPT","DRNT","DSPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 22000 },
  { name: "비타 톤업 워터", brand: "구달", category: "toner", key_ingredients: '["비타민C","유자","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '["OSPT"]', target_concern: "brightening", price: 14800 },
  { name: "소나무 위드 시카 토너", brand: "라운드랩", category: "toner", key_ingredients: '["소나무추출물","시카","판테놀"]', best_baumann: '["OSPT","DSPT","OSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 15800 },
  { name: "센시티브 토닝 로션", brand: "바이오더마", category: "toner", key_ingredients: '["D.A.F.","글리세린","히알루론산"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 28000 },
  { name: "비타민 C 브라이트닝 토너", brand: "닥터시", category: "toner", key_ingredients: '["비타민C","나이아신아마이드","알부틴"]', best_baumann: '["DRPW","DRPT","ORPW"]', avoid_baumann: '["OSPT","DSPT"]', target_concern: "brightening", price: 21000 },
  { name: "약산성 피하지방 클렌징 토너", brand: "라운드어라운드", category: "toner", key_ingredients: '["녹차","BHA","판테놀"]', best_baumann: '["ORPT","OSPT","ORNT"]', avoid_baumann: '[]', target_concern: "pore", price: 11800 },
  { name: "리페어 토너", brand: "피지오겔", category: "toner", key_ingredients: '["세라마이드","스쿠알란","글리세린"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 25000 },
  { name: "모공 토닝 패드", brand: "넘버즈인", category: "toner", key_ingredients: '["BHA","PHA","위치하젤"]', best_baumann: '["ORPT","ORPW","OSPT"]', avoid_baumann: '["DSPT","DSNT"]', target_concern: "pore", price: 15800 },
  { name: "히알루론산 워터리 토너", brand: "이즈앤트리", category: "toner", key_ingredients: '["히알루론산","판테놀","알란토인"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "hydration", price: 14800 },
  { name: "약산성 카밀레 토너", brand: "이소이", category: "toner", key_ingredients: '["카밀레","알로에","글리세린"]', best_baumann: '["DSNT","DSPT","OSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 22000 },
  { name: "유자 비타C 토너 세럼", brand: "스킨푸드", category: "toner", key_ingredients: '["유자추출물","비타민C","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '["OSPT"]', target_concern: "brightening", price: 16000 },
  { name: "콜라겐 파워 리프팅 토너", brand: "에뛰드", category: "toner", key_ingredients: '["콜라겐","펩타이드","히알루론산"]', best_baumann: '["DSPW","DRPW","DSNW"]', avoid_baumann: '[]', target_concern: "elasticity", price: 18500 },
  { name: "화이트 트러플 퍼스트 스프레이 세럼", brand: "달바", category: "toner", key_ingredients: '["화이트트러플","나이아신아마이드","히알루론산"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 38000 },
  { name: "하트리프 스팟 패드 카밍터치", brand: "아비브", category: "toner", key_ingredients: '["어성초","판테놀","알란토인"]', best_baumann: '["OSPT","OSNT","OSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 24000 },
  { name: "빈 에센스", brand: "믹순", category: "toner", key_ingredients: '["발효대두추출물","석류발효","히알루론산"]', best_baumann: '["DRPT","DSPT","DRNT"]', avoid_baumann: '[]', target_concern: "nourish", price: 35000 },
  { name: "풀 핏 프로폴리스 시너지 토너", brand: "코스알엑스", category: "toner", key_ingredients: '["프로폴리스","나이아신아마이드","판테놀"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "nourish", price: 17800 },
  { name: "쌀겨 세럼 토너", brand: "한율", category: "toner", key_ingredients: '["쌀겨추출물","세라마이드","히알루론산"]', best_baumann: '["DSPT","DRPT","DSPW"]', avoid_baumann: '[]', target_concern: "barrier", price: 23000 },
  { name: "페어리 미스트 토너", brand: "브링그린", category: "toner", key_ingredients: '["티트리","CICA","살리실산"]', best_baumann: '["OSPT","ORPT","OSPW"]', avoid_baumann: '["DSPT"]', target_concern: "acne", price: 14800 },
  { name: "글로우 래디언스 토너", brand: "바닐라코", category: "toner", key_ingredients: '["나이아신아마이드","비타민C","글루타치온"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 19800 },
  { name: "씨 스킨 세라마이드 에센스 토너", brand: "아이오페", category: "toner", key_ingredients: '["세라마이드","스쿠알란","히알루론산"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 35000 },
  { name: "칼라민 토너", brand: "에이바이봄", category: "toner", key_ingredients: '["칼라민","판테놀","알란토인"]', best_baumann: '["OSPT","OSPW","OSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 18000 },
  { name: "로즈워터 토너", brand: "마몽드", category: "toner", key_ingredients: '["다마스크로즈워터","히알루론산","글리세린"]', best_baumann: '["DSNT","DRNT","DSPT"]', avoid_baumann: '[]', target_concern: "hydration", price: 16000 },
  { name: "약모밀 수딩 젤 토너", brand: "아로마티카", category: "toner", key_ingredients: '["카밀레","알로에","판테놀"]', best_baumann: '["DSNT","OSNT","DSPT"]', avoid_baumann: '[]', target_concern: "soothing", price: 19800 },
  { name: "바이탈라이징 에너지 토너", brand: "미샤", category: "toner", key_ingredients: '["카페인","나이아신아마이드","히알루론산"]', best_baumann: '["DRNT","DRPT","ORNT"]', avoid_baumann: '[]', target_concern: "energize", price: 15000 },
  { name: "판테놀 시카 배리어 토너", brand: "아누아", category: "toner", key_ingredients: '["판테놀","센텔라","세라마이드"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "barrier", price: 20000 },
  { name: "트러블 릴리프 토너", brand: "세타필", category: "toner", key_ingredients: '["나이아신아마이드","판테놀","글리세린"]', best_baumann: '["DSPT","OSPT","DSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 22000 },
  { name: "글루타치온 700 라이트 토너", brand: "스킨알엑스랩", category: "toner", key_ingredients: '["글루타치온","나이아신아마이드","비타민C"]', best_baumann: '["DRPW","DRPT","ORPW"]', avoid_baumann: '["OSPT"]', target_concern: "brightening", price: 19800 },
  { name: "그린토마토 포어 토닝 앰플 패드", brand: "성분에디터", category: "toner", key_ingredients: '["BHA","PHA","그린토마토"]', best_baumann: '["ORPT","ORPW","OSPT"]', avoid_baumann: '["DSPT","DSNT"]', target_concern: "pore", price: 19800 },
  { name: "소이 밀크 토너", brand: "글리코어", category: "toner", key_ingredients: '["두유추출물","펩타이드","히알루론산"]', best_baumann: '["DSPT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "hydration", price: 16800 },
  { name: "허니 글로우 토너", brand: "파파레서피", category: "toner", key_ingredients: '["프로폴리스","꿀","나이아신아마이드"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "nourish", price: 18800 },
  { name: "참마 비건 밀크 토너", brand: "이즈앤트리", category: "toner", key_ingredients: '["참마추출물","히알루론산","세라마이드"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "hydration", price: 16000 },
  { name: "비피다 바이옴 토너", brand: "마녀공장", category: "toner", key_ingredients: '["비피다","갈락토미세스","판테놀"]', best_baumann: '["DSPT","DRPT","DSPW"]', avoid_baumann: '[]', target_concern: "repair", price: 20000 },
  { name: "씨카 쿨링 토너", brand: "VT코스메틱", category: "toner", key_ingredients: '["센텔라","멘톨","판테놀"]', best_baumann: '["OSPT","ORPT","OSNT"]', avoid_baumann: '["DSPT"]', target_concern: "soothing", price: 14800 },

  // ═══════════════════════════════════════════════════════════════════════════
  // 세럼 (50)
  // ═══════════════════════════════════════════════════════════════════════════
  { name: "다이브인 저분자 히알루론산 세럼", brand: "토리든", category: "serum", key_ingredients: '["히알루론산","판테놀","알란토인"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 22000 },
  { name: "스네일 뮤신 96% 파워 에센스", brand: "코스알엑스", category: "serum", key_ingredients: '["달팽이뮤신","나이아신아마이드","히알루론산"]', best_baumann: '["DSPT","DSPW","DRPT"]', avoid_baumann: '[]', target_concern: "repair", price: 17800 },
  { name: "PDRN 히알루론산 캡슐 100 세럼", brand: "아누아", category: "serum", key_ingredients: '["PDRN","히알루론산","판테놀"]', best_baumann: '["DSPW","DSPT","DRPW"]', avoid_baumann: '[]', target_concern: "repair", price: 25000 },
  { name: "청귤 비타C 잡티 케어 세럼 알파", brand: "구달", category: "serum", key_ingredients: '["비타민C","나이아신아마이드","청귤추출물"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '["OSPT"]', target_concern: "brightening", price: 18800 },
  { name: "리얼 히알루로닉 블루 100 앰플", brand: "웰라쥬", category: "serum", key_ingredients: '["히알루론산","판테놀","나이아신아마이드"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 22000 },
  { name: "PDRN 핑크앰플", brand: "메디큐브", category: "serum", key_ingredients: '["PDRN","글루타치온","나이아신아마이드"]', best_baumann: '["DSPW","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "repair", price: 38000 },
  { name: "마다가스카르 센텔라 앰플", brand: "스킨1004", category: "serum", key_ingredients: '["센텔라","마데카소사이드","판테놀"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 19000 },
  { name: "그린토마토 NMN 포어 리프팅 앰플", brand: "성분에디터", category: "serum", key_ingredients: '["NMN","그린토마토","나이아신아마이드"]', best_baumann: '["ORPT","ORPW","OSPT"]', avoid_baumann: '[]', target_concern: "pore", price: 25000 },
  { name: "리들샷 100", brand: "VT코스메틱", category: "serum", key_ingredients: '["시카리들","센텔라","판테놀"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '["DSPT","OSPT"]', target_concern: "texture", price: 32000 },
  { name: "비타C 13 세럼", brand: "토리든", category: "serum", key_ingredients: '["비타민C","나이아신아마이드","판테놀"]', best_baumann: '["DRPW","DRPT","ORPW"]', avoid_baumann: '["DSPT","OSPT"]', target_concern: "brightening", price: 21000 },
  { name: "하이퍼 글레이즈 세럼", brand: "넘버즈인", category: "serum", key_ingredients: '["글루타치온","나이아신아마이드","비타민C"]', best_baumann: '["DRPW","DRPT","DSPW"]', avoid_baumann: '[]', target_concern: "brightening", price: 22000 },
  { name: "프로폴리스 에너지 앰플", brand: "코스알엑스", category: "serum", key_ingredients: '["프로폴리스","나이아신아마이드","판테놀"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "nourish", price: 22500 },
  { name: "레티놀 인텐스 리모델링 세럼", brand: "토리든", category: "serum", key_ingredients: '["레티놀","펩타이드","세라마이드"]', best_baumann: '["DRPW","DRPT","ORNW"]', avoid_baumann: '["OSPT","OSPW","DSPT"]', target_concern: "wrinkle", price: 28000 },
  { name: "비피다 바이옴 앰플", brand: "마녀공장", category: "serum", key_ingredients: '["비피다","갈락토미세스","나이아신아마이드"]', best_baumann: '["DSPT","DRPT","DSPW"]', avoid_baumann: '[]', target_concern: "repair", price: 25000 },
  { name: "하이퍼 쌀 토닝 앰플", brand: "넘버즈인", category: "serum", key_ingredients: '["쌀추출물","나이아신아마이드","알부틴"]', best_baumann: '["DRPW","DRPT","DSPW"]', avoid_baumann: '[]', target_concern: "brightening", price: 19800 },
  { name: "히알루론산 수분 에센스", brand: "이즈앤트리", category: "serum", key_ingredients: '["히알루론산","판테놀","센텔라"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 14800 },
  { name: "마데카소사이드 시카 세럼", brand: "스킨1004", category: "serum", key_ingredients: '["마데카소사이드","센텔라","판테놀"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 16500 },
  { name: "블레미쉬 케어 업 세럼", brand: "이소이", category: "serum", key_ingredients: '["로즈오일","알부틴","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 38000 },
  { name: "그린티 씨드 세럼", brand: "이니스프리", category: "serum", key_ingredients: '["녹차씨오일","녹차추출물","스쿠알란"]', best_baumann: '["DRNT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "hydration", price: 27000 },
  { name: "어드밴스드 스네일 래디언스 듀얼 에센스", brand: "코스알엑스", category: "serum", key_ingredients: '["달팽이뮤신","나이아신아마이드","알부틴"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 24800 },
  { name: "펩타이드 바운스 안티링클 세럼", brand: "메디큐브", category: "serum", key_ingredients: '["펩타이드","나이아신아마이드","아데노신"]', best_baumann: '["DRPW","DSPW","DRNW"]', avoid_baumann: '[]', target_concern: "wrinkle", price: 35000 },
  { name: "콜라겐 앰플", brand: "에뛰드", category: "serum", key_ingredients: '["콜라겐","펩타이드","히알루론산"]', best_baumann: '["DSPW","DRPW","DSNW"]', avoid_baumann: '[]', target_concern: "elasticity", price: 20000 },
  { name: "판테놀 시카 밤 앰플", brand: "아누아", category: "serum", key_ingredients: '["판테놀","센텔라","세라마이드"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 22000 },
  { name: "토코페롤 멀티 비타민 앰플", brand: "클레어스", category: "serum", key_ingredients: '["비타민E","비타민C","스쿠알란"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "nourish", price: 21000 },
  { name: "갈락토미세스 95 토닝 에센스", brand: "마녀공장", category: "serum", key_ingredients: '["갈락토미세스","나이아신아마이드","히알루론산"]', best_baumann: '["DRPT","DRNT","DSPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 19800 },
  { name: "알로에 BHA 스킨 트너 세럼", brand: "브링그린", category: "serum", key_ingredients: '["알로에","BHA","나이아신아마이드"]', best_baumann: '["ORPT","OSPT","ORNT"]', avoid_baumann: '["DSPT"]', target_concern: "pore", price: 15800 },
  { name: "무 에센스", brand: "믹순", category: "serum", key_ingredients: '["무추출물","히알루론산","글리세린"]', best_baumann: '["DSPT","DSNT","DRNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 28000 },
  { name: "나이아신아마이드 10% 세럼", brand: "코스알엑스", category: "serum", key_ingredients: '["나이아신아마이드","아연","히알루론산"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 14800 },
  { name: "시카 리페어 세럼", brand: "닥터자르트", category: "serum", key_ingredients: '["센텔라","판테놀","마데카소사이드"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 38000 },
  { name: "콜라겐 드림 세럼", brand: "에뛰드", category: "serum", key_ingredients: '["콜라겐","엘라스틴","히알루론산"]', best_baumann: '["DSPW","DRPW","DSNW"]', avoid_baumann: '[]', target_concern: "elasticity", price: 22000 },
  { name: "레티놀 0.5% 세럼", brand: "달바", category: "serum", key_ingredients: '["레티놀","스쿠알란","비타민E"]', best_baumann: '["DRPW","DRPT","ORNW"]', avoid_baumann: '["OSPT","DSPT"]', target_concern: "wrinkle", price: 35000 },
  { name: "글루타치온 나이아신 브라이트닝 세럼", brand: "바이오더마", category: "serum", key_ingredients: '["글루타치온","나이아신아마이드","비타민C"]', best_baumann: '["DRPW","DRPT","ORPW"]', avoid_baumann: '[]', target_concern: "brightening", price: 32000 },
  { name: "AHA/BHA 클래리파잉 트리트먼트 토너", brand: "코스알엑스", category: "serum", key_ingredients: '["AHA","BHA","나이아신아마이드"]', best_baumann: '["ORPT","ORPW","ORNT"]', avoid_baumann: '["DSPT","OSPT"]', target_concern: "pore", price: 15800 },
  { name: "세라마이드 리퀴드", brand: "홀리카홀리카", category: "serum", key_ingredients: '["세라마이드","히알루론산","판테놀"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 16800 },
  { name: "BHA 블랙헤드 파워 리퀴드", brand: "코스알엑스", category: "serum", key_ingredients: '["BHA","나이아신아마이드","윌로우바크"]', best_baumann: '["ORPT","ORPW","OSPT"]', avoid_baumann: '["DSPT","DSNT"]', target_concern: "pore", price: 18800 },
  { name: "히알루론산 100 앰플", brand: "이즈앤트리", category: "serum", key_ingredients: '["히알루론산","판테놀","알란토인"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 12800 },
  { name: "어성초 수딩 앰플", brand: "아누아", category: "serum", key_ingredients: '["어성초","판테놀","알란토인"]', best_baumann: '["OSPT","OSPW","OSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 20000 },
  { name: "비건 콜라겐 앰플", brand: "에뛰드", category: "serum", key_ingredients: '["비건콜라겐","펩타이드","히알루론산"]', best_baumann: '["DSPW","DRPW","DSNW"]', avoid_baumann: '[]', target_concern: "elasticity", price: 19800 },
  { name: "스쿠알란 100 오일세럼", brand: "이즈앤트리", category: "serum", key_ingredients: '["스쿠알란","비타민E","호호바오일"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '["ORPT","ORPW"]', target_concern: "nourish", price: 14800 },
  { name: "레티놀 시카 리뉴 세럼", brand: "스킨1004", category: "serum", key_ingredients: '["레티놀","센텔라","판테놀"]', best_baumann: '["DRPW","DSPW","DRNW"]', avoid_baumann: '["OSPT"]', target_concern: "wrinkle", price: 22000 },
  { name: "빨간 펩타이드 앰플", brand: "에스트라", category: "serum", key_ingredients: '["펩타이드","나이아신아마이드","아데노신"]', best_baumann: '["DSPW","DRPW","DSNW"]', avoid_baumann: '[]', target_concern: "wrinkle", price: 28000 },
  { name: "티트리 90 포어 리파이닝 세럼", brand: "브링그린", category: "serum", key_ingredients: '["티트리","나이아신아마이드","살리실산"]', best_baumann: '["OSPT","ORPT","OSPW"]', avoid_baumann: '["DSPT"]', target_concern: "acne", price: 15800 },
  { name: "세럼 인 크림 아쿠아", brand: "에스네이처", category: "serum", key_ingredients: '["히알루론산","스쿠알란","판테놀"]', best_baumann: '["DSPT","DSNT","DRNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 25000 },
  { name: "화이트 트러플 비건 선 세럼", brand: "달바", category: "serum", key_ingredients: '["화이트트러플","히알루론산","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 32000 },
  { name: "아토베리어 퍼스트 에센스", brand: "에스트라", category: "serum", key_ingredients: '["세라마이드","콜레스테롤","지방산"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 25000 },
  { name: "클리어 비타C 올 클린 앰플", brand: "구달", category: "serum", key_ingredients: '["비타민C","유자","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '["OSPT"]', target_concern: "brightening", price: 22000 },
  { name: "참마 비건 콜라겐 에센스", brand: "이즈앤트리", category: "serum", key_ingredients: '["참마추출물","비건콜라겐","히알루론산"]', best_baumann: '["DSPW","DSPT","DRPW"]', avoid_baumann: '[]', target_concern: "elasticity", price: 18800 },
  { name: "징크 세바세 수딩 세럼", brand: "닥터지", category: "serum", key_ingredients: '["아연","시카","나이아신아마이드"]', best_baumann: '["OSPT","ORPT","OSPW"]', avoid_baumann: '[]', target_concern: "acne", price: 22000 },
  { name: "PDRN 앰플", brand: "VT코스메틱", category: "serum", key_ingredients: '["PDRN","히알루론산","나이아신아마이드"]', best_baumann: '["DSPW","DSPT","DRPW"]', avoid_baumann: '[]', target_concern: "repair", price: 28000 },

  // ═══════════════════════════════════════════════════════════════════════════
  // 크림 (50)
  // ═══════════════════════════════════════════════════════════════════════════
  { name: "아토베리어 365 크림", brand: "에스트라", category: "cream", key_ingredients: '["세라마이드","콜레스테롤","지방산"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 31000 },
  { name: "아쿠아 스쿠알란 수분크림", brand: "에스네이처", category: "cream", key_ingredients: '["스쿠알란","히알루론산","판테놀"]', best_baumann: '["DSPT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "hydration", price: 25000 },
  { name: "자작나무 수분크림", brand: "라운드랩", category: "cream", key_ingredients: '["자작나무수액","세라마이드","판테놀"]', best_baumann: '["DSNT","DSPT","OSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 18000 },
  { name: "리얼 히알루로닉 수딩 크림", brand: "웰라쥬", category: "cream", key_ingredients: '["히알루론산","판테놀","세라마이드"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 25000 },
  { name: "다이브인 저분자 히알루론산 수딩 크림", brand: "토리든", category: "cream", key_ingredients: '["히알루론산","판테놀","알란토인"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 20000 },
  { name: "세라마이드 아토 집중 크림", brand: "일리윤", category: "cream", key_ingredients: '["세라마이드","판테놀","스쿠알란"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 15000 },
  { name: "세라베 모이스처라이징 크림", brand: "세라베", category: "cream", key_ingredients: '["세라마이드","히알루론산","나이아신아마이드"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 19800 },
  { name: "레드 블레미쉬 클리어 수딩 크림", brand: "닥터지", category: "cream", key_ingredients: '["시카","센텔라","판테놀"]', best_baumann: '["OSPT","DSPT","OSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 36000 },
  { name: "시카 리페어 크림", brand: "닥터자르트", category: "cream", key_ingredients: '["센텔라","판테놀","마데카소사이드"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 32000 },
  { name: "PDRN 히알루론산 100 수분크림", brand: "아누아", category: "cream", key_ingredients: '["PDRN","히알루론산","세라마이드"]', best_baumann: '["DSPW","DSPT","DRPW"]', avoid_baumann: '[]', target_concern: "repair", price: 28000 },
  { name: "다이브인 저분자 히알루론산 크림", brand: "토리든", category: "cream", key_ingredients: '["히알루론산","세라마이드","판테놀"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 22000 },
  { name: "세타필 모이스처라이징 크림", brand: "세타필", category: "cream", key_ingredients: '["글리세린","해바라기오일","나이아신아마이드"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 22000 },
  { name: "워터핏 8중 수분착붙 크림", brand: "리브엠", category: "cream", key_ingredients: '["히알루론산","세라마이드","판테놀"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 28000 },
  { name: "레드 수딩 AI 리페어 크림", brand: "피지오겔", category: "cream", key_ingredients: '["세라마이드","스쿠알란","바이오미믹"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 25000 },
  { name: "익스트림 크림", brand: "리얼배리어", category: "cream", key_ingredients: '["세라마이드","MLE기술","스쿠알란"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 28000 },
  { name: "어드밴스드 스네일 92 크림", brand: "코스알엑스", category: "cream", key_ingredients: '["달팽이뮤신","아데노신","판테놀"]', best_baumann: '["DSPT","DSPW","DRPT"]', avoid_baumann: '[]', target_concern: "repair", price: 18500 },
  { name: "레티놀 인텐스 크림", brand: "이니스프리", category: "cream", key_ingredients: '["레티놀","시카","세라마이드"]', best_baumann: '["DRPW","DRPT","DRNW"]', avoid_baumann: '["OSPT","DSPT"]', target_concern: "wrinkle", price: 25000 },
  { name: "알로에 수딩 젤크림", brand: "홀리카홀리카", category: "cream", key_ingredients: '["알로에","히알루론산","판테놀"]', best_baumann: '["OSNT","OSPT","ORNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 9800 },
  { name: "리얼 콜라겐 보습 크림", brand: "에뛰드", category: "cream", key_ingredients: '["콜라겐","세라마이드","히알루론산"]', best_baumann: '["DSPW","DRPW","DSNW"]', avoid_baumann: '[]', target_concern: "elasticity", price: 18500 },
  { name: "판테놀 시카 밤 크림", brand: "아누아", category: "cream", key_ingredients: '["판테놀","센텔라","세라마이드"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 22000 },
  { name: "수분 가득 콜라겐 크림", brand: "에뛰드", category: "cream", key_ingredients: '["콜라겐","히알루론산","글리세린"]', best_baumann: '["DSPW","DSPT","DSNW"]', avoid_baumann: '[]', target_concern: "elasticity", price: 16800 },
  { name: "소나무 진정 수분크림", brand: "라운드랩", category: "cream", key_ingredients: '["소나무추출물","시카","판테놀"]', best_baumann: '["OSPT","DSPT","OSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 18000 },
  { name: "바닐라코 클린잇제로 크림", brand: "바닐라코", category: "cream", key_ingredients: '["세라마이드","판테놀","히알루론산"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "hydration", price: 22000 },
  { name: "마데카 크림", brand: "센텔리안24", category: "cream", key_ingredients: '["마데카소사이드","센텔라","판테놀"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 25000 },
  { name: "제주 한라봉 비타민 크림", brand: "이니스프리", category: "cream", key_ingredients: '["비타민C","한라봉추출물","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '["OSPT"]', target_concern: "brightening", price: 20000 },
  { name: "펩타이드 아이크림", brand: "메디큐브", category: "cream", key_ingredients: '["펩타이드","나이아신아마이드","카페인"]', best_baumann: '["DSPW","DRPW","DSNW"]', avoid_baumann: '[]', target_concern: "wrinkle", price: 32000 },
  { name: "세라마이드 아토 로션", brand: "일리윤", category: "cream", key_ingredients: '["세라마이드","판테놀","스쿠알란"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "barrier", price: 12800 },
  { name: "시카 밤", brand: "닥터자르트", category: "cream", key_ingredients: '["센텔라","마데카소사이드","판테놀"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 28000 },
  { name: "아쿠아 오아시스 크림", brand: "에스네이처", category: "cream", key_ingredients: '["스쿠알란","히알루론산","세라마이드"]', best_baumann: '["DSPT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "hydration", price: 28000 },
  { name: "스네일 뮤신 92% 크림", brand: "코스알엑스", category: "cream", key_ingredients: '["달팽이뮤신","세라마이드","판테놀"]', best_baumann: '["DSPT","DSPW","DRPT"]', avoid_baumann: '[]', target_concern: "repair", price: 19800 },
  { name: "비건 그린 크림", brand: "에뛰드", category: "cream", key_ingredients: '["시카","티트리","판테놀"]', best_baumann: '["OSPT","OSNT","ORPT"]', avoid_baumann: '[]', target_concern: "soothing", price: 16800 },
  { name: "리페어 크림", brand: "피지오겔", category: "cream", key_ingredients: '["세라마이드","스쿠알란","글리세린"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 28000 },
  { name: "세라마이드 크림", brand: "토리든", category: "cream", key_ingredients: '["세라마이드","히알루론산","판테놀"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 22000 },
  { name: "수퍼 히알루론 크림", brand: "아이소이", category: "cream", key_ingredients: '["히알루론산","스쿠알란","세라마이드"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 35000 },
  { name: "그린 모이스처 크림", brand: "브링그린", category: "cream", key_ingredients: '["티트리","센텔라","판테놀"]', best_baumann: '["OSPT","OSNT","OSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 16800 },
  { name: "비타민 나이아신 크림", brand: "미샤", category: "cream", key_ingredients: '["나이아신아마이드","비타민C","글리세린"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 18000 },
  { name: "로즈 워터 수딩 젤크림", brand: "마몽드", category: "cream", key_ingredients: '["다마스크로즈워터","히알루론산","알로에"]', best_baumann: '["DSNT","DRNT","OSNT"]', avoid_baumann: '[]', target_concern: "hydration", price: 18000 },
  { name: "콜라겐 파워 리프팅 크림", brand: "에뛰드", category: "cream", key_ingredients: '["콜라겐","엘라스틴","아데노신"]', best_baumann: '["DSPW","DRPW","DSNW"]', avoid_baumann: '[]', target_concern: "elasticity", price: 25000 },
  { name: "알부틴 나이아신 브라이트닝 크림", brand: "닥터시", category: "cream", key_ingredients: '["알부틴","나이아신아마이드","비타민C"]', best_baumann: '["DRPW","DRPT","ORPW"]', avoid_baumann: '[]', target_concern: "brightening", price: 28000 },
  { name: "씨카 밤", brand: "스킨1004", category: "cream", key_ingredients: '["센텔라","판테놀","마데카소사이드"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 18000 },

  // ═══════════════════════════════════════════════════════════════════════════
  // 선크림 (50)
  // ═══════════════════════════════════════════════════════════════════════════
  { name: "자작나무 수분 선크림 SPF50+", brand: "라운드랩", category: "sunscreen", key_ingredients: '["자작나무수액","히알루론산","센텔라"]', best_baumann: '["DSPT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 16800 },
  { name: "릴리프 선 라이스 프로바이오틱스 SPF50+", brand: "조선미녀", category: "sunscreen", key_ingredients: '["쌀추출물","프로바이오틱스","나이아신아마이드"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 18000 },
  { name: "그린 마일드 업 선 플러스 SPF50+", brand: "닥터지", category: "sunscreen", key_ingredients: '["센텔라","판테놀","비타민E"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 18000 },
  { name: "아쿠아 리치 워터리 에센스 SPF50+", brand: "비오레", category: "sunscreen", key_ingredients: '["히알루론산","로얄젤리","구연산"]', best_baumann: '["ORNT","ORPT","OSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 12800 },
  { name: "에어리 선스틱 SPF50+", brand: "토리든", category: "sunscreen", key_ingredients: '["히알루론산","센텔라","비타민E"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 16500 },
  { name: "워터풀 에센스 선크림 SPF50+", brand: "달바", category: "sunscreen", key_ingredients: '["화이트트러플","히알루론산","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 32000 },
  { name: "히알루시카 워터핏 선세럼 SPF50+", brand: "스킨1004", category: "sunscreen", key_ingredients: '["히알루론산","센텔라","나이아신아마이드"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 21000 },
  { name: "퀵 선스틱 프로텍션 바 SPF50+", brand: "아비브", category: "sunscreen", key_ingredients: '["어성초","판테놀","비타민E"]', best_baumann: '["OSPT","DSPT","OSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 22000 },
  { name: "톤업 선크림 SPF50+", brand: "라운드랩", category: "sunscreen", key_ingredients: '["자작나무수액","나이아신아마이드","센텔라"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 18000 },
  { name: "다이브인 워터리 선크림 SPF50+", brand: "토리든", category: "sunscreen", key_ingredients: '["히알루론산","판테놀","센텔라"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 18000 },
  { name: "산들산들 선크림 SPF50+", brand: "스킨1004", category: "sunscreen", key_ingredients: '["센텔라","히알루론산","나이아신아마이드"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 16000 },
  { name: "모이스처 선크림 SPF50+", brand: "이즈앤트리", category: "sunscreen", key_ingredients: '["히알루론산","센텔라","스쿠알란"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 14800 },
  { name: "선밀크 SPF50+", brand: "아이소이", category: "sunscreen", key_ingredients: '["알로에","불가리안로즈","비타민E"]', best_baumann: '["DSNT","DRNT","OSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 25000 },
  { name: "UV 디펜스 미 데일리 선크림 SPF50+", brand: "라로슈포제", category: "sunscreen", key_ingredients: '["나이아신아마이드","비타민E","라로슈포제온천수"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 28000 },
  { name: "에센스 인 선밀크 SPF50+", brand: "구달", category: "sunscreen", key_ingredients: '["어성초","히알루론산","나이아신아마이드"]', best_baumann: '["OSPT","OSNT","ORPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 15800 },
  { name: "보송 페이스 앤 바디 선스틱 SPF50+", brand: "식물나라", category: "sunscreen", key_ingredients: '["티타늄디옥사이드","징크옥사이드","비타민E"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 9800 },
  { name: "비건 워터풀 핑크 톤업 선크림 SPF50+", brand: "달바", category: "sunscreen", key_ingredients: '["화이트트러플","나이아신아마이드","글리세린"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 28000 },
  { name: "UV 프로텍터 톤업 선크림 SPF50+", brand: "헤라", category: "sunscreen", key_ingredients: '["나이아신아마이드","히알루론산","비타민E"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 35000 },
  { name: "레이전 썬스크린 100 SPF50+", brand: "셀퓨전씨", category: "sunscreen", key_ingredients: '["센텔라","나이아신아마이드","판테놀"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 22000 },
  { name: "수퍼 에어핏 선크림 SPF50+", brand: "미샤", category: "sunscreen", key_ingredients: '["히알루론산","글리세린","비타민E"]', best_baumann: '["ORNT","ORPT","DRNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 12800 },
  { name: "시카 수딩 선크림 SPF50+", brand: "닥터자르트", category: "sunscreen", key_ingredients: '["센텔라","판테놀","마데카소사이드"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 28000 },
  { name: "노세범 선크림 SPF50+", brand: "이니스프리", category: "sunscreen", key_ingredients: '["제주화산송이","민트","징크옥사이드"]', best_baumann: '["ORPT","ORNT","OSPT"]', avoid_baumann: '["DSPT"]', target_concern: "uv_protect", price: 12800 },
  { name: "수분 톤업 선세럼 SPF50+", brand: "에스네이처", category: "sunscreen", key_ingredients: '["스쿠알란","히알루론산","나이아신아마이드"]', best_baumann: '["DSPT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 22000 },
  { name: "어성초 선크림 SPF50+", brand: "아누아", category: "sunscreen", key_ingredients: '["어성초","판테놀","나이아신아마이드"]', best_baumann: '["OSPT","OSNT","OSPW"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 18000 },
  { name: "비타민 선크림 SPF50+", brand: "구달", category: "sunscreen", key_ingredients: '["비타민C","유자","히알루론산"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 16800 },
  { name: "데일리 마일드 선크림 SPF50+", brand: "에뛰드", category: "sunscreen", key_ingredients: '["히알루론산","알로에","비타민E"]', best_baumann: '["DSNT","DRNT","OSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 11800 },
  { name: "시카 데일리 선크림 SPF50+", brand: "스킨1004", category: "sunscreen", key_ingredients: '["센텔라","히알루론산","판테놀"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 18000 },
  { name: "히알루론 워터리 선젤 SPF50+", brand: "이즈앤트리", category: "sunscreen", key_ingredients: '["히알루론산","알로에","판테놀"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 16800 },
  { name: "UV 에센스 하이 선크림 SPF50+", brand: "마몽드", category: "sunscreen", key_ingredients: '["로즈워터","히알루론산","비타민E"]', best_baumann: '["DSNT","DRNT","DSPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 18000 },
  { name: "센텔라 그린 레벨 세이프 선 SPF50+", brand: "브링그린", category: "sunscreen", key_ingredients: '["센텔라","티트리","판테놀"]', best_baumann: '["OSPT","OSNT","DSPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 14800 },
  { name: "모노 데일리 선크림 SPF50+", brand: "아리따움", category: "sunscreen", key_ingredients: '["히알루론산","비타민E","글리세린"]', best_baumann: '["DRNT","DSNT","ORNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 14800 },
  { name: "알로에 수딩 선크림 SPF50+", brand: "홀리카홀리카", category: "sunscreen", key_ingredients: '["알로에","히알루론산","판테놀"]', best_baumann: '["DSNT","OSNT","DRNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 9800 },
  { name: "PDRN 선크림 SPF50+", brand: "메디큐브", category: "sunscreen", key_ingredients: '["PDRN","나이아신아마이드","히알루론산"]', best_baumann: '["DSPW","DSPT","DRPW"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 28000 },
  { name: "리들샷 선크림 SPF50+", brand: "VT코스메틱", category: "sunscreen", key_ingredients: '["시카리들","센텔라","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 22000 },
  { name: "소나무 선크림 SPF50+", brand: "라운드랩", category: "sunscreen", key_ingredients: '["소나무추출물","시카","판테놀"]', best_baumann: '["OSPT","DSPT","OSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 16800 },
  { name: "스네일 뮤신 선크림 SPF50+", brand: "코스알엑스", category: "sunscreen", key_ingredients: '["달팽이뮤신","히알루론산","나이아신아마이드"]', best_baumann: '["DSPT","DSPW","DRPT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 18800 },
  { name: "글루타치온 톤업 선크림 SPF50+", brand: "넘버즈인", category: "sunscreen", key_ingredients: '["글루타치온","나이아신아마이드","비타민C"]', best_baumann: '["DRPW","DRPT","ORPW"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 19800 },
  { name: "클리어 선크림 SPF50+", brand: "피지오겔", category: "sunscreen", key_ingredients: '["세라마이드","글리세린","비타민E"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 25000 },
  { name: "워터 에센스 선스크린 SPF50+", brand: "마녀공장", category: "sunscreen", key_ingredients: '["갈락토미세스","히알루론산","나이아신아마이드"]', best_baumann: '["DRPT","DSPT","DRNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 16800 },
  { name: "세라마이드 선크림 SPF50+", brand: "일리윤", category: "sunscreen", key_ingredients: '["세라마이드","판테놀","스쿠알란"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "uv_protect", price: 15800 },

  // ═══════════════════════════════════════════════════════════════════════════
  // 클렌저 (50)
  // ═══════════════════════════════════════════════════════════════════════════
  { name: "녹두 약산성 클렌징폼", brand: "비플레인", category: "cleanser", key_ingredients: '["녹두","판테놀","알란토인"]', best_baumann: '["DSPT","OSPT","DSNT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 13800 },
  { name: "다이브인 클렌징 폼", brand: "토리든", category: "cleanser", key_ingredients: '["히알루론산","판테놀","알란토인"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "cleansing", price: 12000 },
  { name: "1025 독도 클렌저", brand: "라운드랩", category: "cleanser", key_ingredients: '["해양심층수","히알루론산","판테놀"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 13000 },
  { name: "로우 pH 굿모닝 젤 클렌저", brand: "코스알엑스", category: "cleanser", key_ingredients: '["티트리","BHA","판테놀"]', best_baumann: '["OSPT","ORPT","OSNT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 10800 },
  { name: "퍼펙트 휩 센카 클렌징 폼", brand: "센카", category: "cleanser", key_ingredients: '["히알루론산","실크","꿀"]', best_baumann: '["DRNT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 6800 },
  { name: "어성초 클렌징 폼", brand: "아누아", category: "cleanser", key_ingredients: '["어성초","BHA","판테놀"]', best_baumann: '["OSPT","ORPT","OSPW"]', avoid_baumann: '[]', target_concern: "acne", price: 14000 },
  { name: "시카 클렌징 폼", brand: "닥터자르트", category: "cleanser", key_ingredients: '["센텔라","판테놀","아미노산"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 18000 },
  { name: "그린티 아미노 클렌징 폼", brand: "이니스프리", category: "cleanser", key_ingredients: '["녹차","아미노산","글리세린"]', best_baumann: '["DRNT","DSNT","ORNT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 9800 },
  { name: "독도 클렌징 워터", brand: "라운드랩", category: "cleanser", key_ingredients: '["해양심층수","히알루론산","판테놀"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 13800 },
  { name: "퓨어핏 시카 클렌저", brand: "스킨1004", category: "cleanser", key_ingredients: '["센텔라","티트리","알란토인"]', best_baumann: '["DSPT","OSPT","DSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 13000 },
  { name: "퓨어 클렌징 오일", brand: "마녀공장", category: "cleanser", key_ingredients: '["비타민E","호호바오일","올리브오일"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 29000 },
  { name: "어성초 포어 컨트롤 클렌징 오일", brand: "아누아", category: "cleanser", key_ingredients: '["어성초","호호바오일","BHA"]', best_baumann: '["OSPT","ORPT","OSPW"]', avoid_baumann: '[]', target_concern: "pore", price: 20000 },
  { name: "클린잇제로 오리지널 핑크", brand: "바닐라코", category: "cleanser", key_ingredients: '["제로밸런스기술","비타민E","세라마이드"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 18000 },
  { name: "소다 포어 클렌징 폼", brand: "홀리카홀리카", category: "cleanser", key_ingredients: '["베이킹소다","파파인","AHA"]', best_baumann: '["ORPT","ORPW","ORNT"]', avoid_baumann: '["DSPT","OSPT"]', target_concern: "pore", price: 8800 },
  { name: "비타민 클렌징 폼", brand: "구달", category: "cleanser", key_ingredients: '["비타민C","유자","나이아신아마이드"]', best_baumann: '["DRPT","DRPW","ORPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 10800 },
  { name: "참마 비건 밀크 클렌저", brand: "이즈앤트리", category: "cleanser", key_ingredients: '["참마추출물","히알루론산","아미노산"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "cleansing", price: 16000 },
  { name: "라미나리아 앰플 클렌징 폼", brand: "시온르", category: "cleanser", key_ingredients: '["라미나리아","히알루론산","판테놀"]', best_baumann: '["DSPT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 16800 },
  { name: "은행 버블 클렌저", brand: "에이닢", category: "cleanser", key_ingredients: '["은행추출물","글리세린","판테놀"]', best_baumann: '["DRNT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 22000 },
  { name: "허브 그린 클렌징 오일", brand: "마녀공장", category: "cleanser", key_ingredients: '["허브추출물","티트리","호호바오일"]', best_baumann: '["OSPT","ORPT","DSPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 16800 },
  { name: "블랙헤드 파워 리퀴드 클렌저", brand: "코스알엑스", category: "cleanser", key_ingredients: '["BHA","티트리","판테놀"]', best_baumann: '["ORPT","ORPW","OSPT"]', avoid_baumann: '["DSPT"]', target_concern: "pore", price: 12800 },
  { name: "약산성 젤 클렌저", brand: "라운드랩", category: "cleanser", key_ingredients: '["해양심층수","아미노산","판테놀"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 12800 },
  { name: "센텔라 버블 클렌저", brand: "스킨1004", category: "cleanser", key_ingredients: '["센텔라","판테놀","알란토인"]', best_baumann: '["DSPT","OSPT","DSNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 14800 },
  { name: "미셀라 클렌징 워터", brand: "바이오더마", category: "cleanser", key_ingredients: '["D.A.F.","글리세린","미셀라"]', best_baumann: '["DSPT","DSNT","OSPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 22000 },
  { name: "레드 블레미쉬 포밍 클렌저", brand: "닥터지", category: "cleanser", key_ingredients: '["시카","센텔라","판테놀"]', best_baumann: '["OSPT","DSPT","OSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 16800 },
  { name: "리얼 약산성 클렌징 폼", brand: "네오젠", category: "cleanser", key_ingredients: '["그린티","아미노산","판테놀"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 14800 },
  { name: "티트리 시카 클렌징 폼", brand: "쏘내추럴", category: "cleanser", key_ingredients: '["티트리","시카","살리실산"]', best_baumann: '["OSPT","ORPT","OSPW"]', avoid_baumann: '["DSPT"]', target_concern: "acne", price: 12800 },
  { name: "히알루론 클렌징 폼", brand: "이즈앤트리", category: "cleanser", key_ingredients: '["히알루론산","아미노산","판테놀"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "cleansing", price: 13800 },
  { name: "스네일 뮤신 젤 클렌저", brand: "코스알엑스", category: "cleanser", key_ingredients: '["달팽이뮤신","BHA","판테놀"]', best_baumann: '["DSPT","OSPT","DRPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 12800 },
  { name: "프로폴리스 버블 클렌저", brand: "코스알엑스", category: "cleanser", key_ingredients: '["프로폴리스","판테놀","글리세린"]', best_baumann: '["DSPT","DSNT","DSPW"]', avoid_baumann: '[]', target_concern: "nourish", price: 14800 },
  { name: "라이스 워터 브라이트 클렌징 폼", brand: "더페이스샵", category: "cleanser", key_ingredients: '["쌀뜨물추출물","나이아신아마이드","세라마이드"]', best_baumann: '["DRPT","DRPW","DSPT"]', avoid_baumann: '[]', target_concern: "brightening", price: 8800 },
  { name: "에그 포어 딥 클렌징 폼", brand: "스킨푸드", category: "cleanser", key_ingredients: '["달걀흰자","BHA","파파인"]', best_baumann: '["ORPT","ORPW","OSPT"]', avoid_baumann: '["DSPT"]', target_concern: "pore", price: 8800 },
  { name: "알로에 클렌징 폼", brand: "홀리카홀리카", category: "cleanser", key_ingredients: '["알로에","히알루론산","글리세린"]', best_baumann: '["DSNT","OSNT","DRNT"]', avoid_baumann: '[]', target_concern: "soothing", price: 7800 },
  { name: "올인원 클렌징 밀크", brand: "한율", category: "cleanser", key_ingredients: '["쌀겨","세라마이드","글리세린"]', best_baumann: '["DSPT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 18000 },
  { name: "블루베리 리얼리스 클렌징 워터", brand: "이니스프리", category: "cleanser", key_ingredients: '["블루베리","히알루론산","판테놀"]', best_baumann: '["DSPT","DRPT","DSNT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 11800 },
  { name: "약산성 클렌징 젤", brand: "아로마티카", category: "cleanser", key_ingredients: '["티트리","로즈마리","아미노산"]', best_baumann: '["OSPT","ORPT","OSNT"]', avoid_baumann: '[]', target_concern: "acne", price: 16800 },
  { name: "세라마이드 수딩 젤 클렌저", brand: "일리윤", category: "cleanser", key_ingredients: '["세라마이드","판테놀","알란토인"]', best_baumann: '["DSPT","DSPW","DSNT"]', avoid_baumann: '[]', target_concern: "barrier", price: 12800 },
  { name: "어성초 77 클렌징 오일", brand: "아누아", category: "cleanser", key_ingredients: '["어성초","호호바오일","비타민E"]', best_baumann: '["OSPT","OSPW","ORPT"]', avoid_baumann: '[]', target_concern: "soothing", price: 18000 },
  { name: "녹차 씨드 크림 클렌징 폼", brand: "이니스프리", category: "cleanser", key_ingredients: '["녹차씨오일","아미노산","글리세린"]', best_baumann: '["DRNT","DSNT","DRPT"]', avoid_baumann: '[]', target_concern: "cleansing", price: 9800 },
  { name: "솔트 클렌저", brand: "에뛰드", category: "cleanser", key_ingredients: '["소금","BHA","글리세린"]', best_baumann: '["ORPT","ORPW","ORNT"]', avoid_baumann: '["DSPT","OSPT"]', target_concern: "pore", price: 11800 },
  { name: "판테놀 클렌징 폼", brand: "아누아", category: "cleanser", key_ingredients: '["판테놀","센텔라","아미노산"]', best_baumann: '["DSPT","OSPT","DSPW"]', avoid_baumann: '[]', target_concern: "soothing", price: 14000 },
];
